language: csharp
solution: ConceptMapMongo/ConceptMapMongo.sln
notifications:
  email:
    on_success: always
    on_failure: always
  slack: srboeingdotnet:GhCzs3W4Gj7eaQ2pLNwIWVCa
mono: none
dotnet: 2.1
script:
  - chmod +x ./deploy.sh
after_success:
  on:
    branch: master
      - /bin/bash ./deploy.sh  