version: "3"
services:
  web:
    build: ./ConceptMapMongo/ConceptMapMongo
    depends_on:
      - db
    expose:
      - "80"    
    labels:
      - "SERVICE_NAME=ConceptMap"
      - "SERVICE_TAGS=ConceptMapTag"
    depends_on:
      - db
      - messagebroker
  db:
    image: "mongo:latest"
  messagebroker:
    image: "rabbitmq:3.7-management"
    # expose:
    #   - "5672"
    #   - "15672"
    network_mode: host
    environment:
      RABBITMQ_DEFAULT_USER: "preety"
      RABBITMQ_DEFAULT_PASS: "preety"  
    
