version: "3"
services:
  web:
    build: ./ConceptMapMongo/ConceptMapMongo
    depends_on:
      - db
    expose:
      - "80"    
    labels:
      - "SERVICE_NAME=ConceptMap"
      - "SERVICE_TAGS=ConceptMapTag"
    depends_on:
      - db
      - messagebroker
    volumes:
      - "/machine_config:/app/machine_config"
    # network_mode: host
  db:
    image: "mongo:latest"
    restart: always
  messagebroker:
    image: "rabbitmq:3.7-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    # network_mode: host
    environment:
      RABBITMQ_DEFAULT_USER: "preety"
      RABBITMQ_DEFAULT_PASS: "preety"