version: "3"
services:
  web:
    build: ./ConceptMapMongo/ConceptMapMongo
    depends_on:
      - db
    ports:
      - "5005:80"    
    labels:
      - "SERVICE_NAME=ConceptMap"
      - "SERVICE_TAGS=ConceptMapTag"
    depends_on:
      - db
      - messagebroker
  db:
    image: "mongo:latest"
  messagebroker:
    image: "rabbitmq:3.7-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "preety"
      RABBITMQ_DEFAULT_PASS: "preety"  
    
